@startuml
'skinparam linetype ortho
skinparam packageStyle rectangle
top to bottom direction

cloud "Financial Institution" {
}

database MTADatabase  {
    artifact SampleData
}

package DataStreamer  {
    NextTick - [DataPreprocessor]
    [SampleTools]
    [InstitutionLink]
    component DataPreprocessor {
    }
    
    [DataStream]
    DataStream *== [DataPreprocessor]
    DataStream *== [DataLink]

    SampleTools -[hidden]-> [DataPreprocessor]
    InstitutionLink -[hidden]-> [DataPreprocessor]

    [DataLink]
    [InstitutionLink] -up-|> [DataLink]
    [SampleTools] -up-|> [DataLink]
    [DataLink] -> NextTick
}


note right of DataStreamer
    The DataStreamer is configured with
    "Data Configuration" and "Model Configuration".
    The external tool is "connected" to the data streamer
end note

"Financial Institution" --> InstitutionLink
SampleTools <--> MTADatabase

artifact "Feature Vector" as fv
DataStream -down-> fv : "run() to serve_feature_vector"

component "External Tool"

DataStreamer --> "External Tool"

package "Model Trainer" {
    [RL Learner]
}
package "Runtime Analytics" {
    [Agent Aggregator]
}
package Backtest


"Runtime Analytics" -up-|> [External Tool]
"Model Trainer" -up-|> [External Tool]
ServeNextVector - [External Tool]
fv -down-> ServeNextVector

"Runtime Analytics" -down-> Backtest

database ModelDatabase {
    artifact ModelParameters
}
[RL Learner] -down-> ModelDatabase
ModelDatabase -up-> [Agent Aggregator]
@end